openapi: 3.0.3
info:
  title: Home Services Marketplace - User API
  description: API to manage users, authentication, and roles in the Home Services Marketplace
  version: 1.0.0

servers:
  - url: https://api.marketplace.com/users
    description: main production server
  - url: https://staging.api.marketplace.com/users
    description: staging server for testing purposes only
  - url: http://localhost:3000/users
    description: local development server

paths:
  /register:
    post:
      summary: Register a new user
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserSchema'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/ValidationError'

  /register/verify:
    get:
      summary: Verify user email using token
      operationId: verifyEmail
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Email verified successfully
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

  /login:
    post:
      summary: Authenticate user and return tokens
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginSchema'
      responses:
        '200':
          description: Tokens returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /token/refresh:
    post:
      summary: Refresh access token using refresh token
      operationId: refreshToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [refresh_token]
              properties:
                refresh_token:
                  type: string
      responses:
        '200':
          description: New access token returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /logout:
    post:
      summary: Revoke refresh token and logout
      operationId: logoutUser
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Logged out successfully
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /password/forgot:
    post:
      summary: Initiate password reset (send reset email)
      operationId: forgotPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email]
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: Password reset initiated
        '422':
          $ref: '#/components/responses/ValidationError'

  /password/reset:
    post:
      summary: Complete password reset using token
      operationId: resetPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [token, newPassword]
              properties:
                token:
                  type: string
                newPassword:
                  type: string
      responses:
        '200':
          description: Password reset successfully
        '400':
          $ref: '#/components/responses/BadRequest'
        '422':
          $ref: '#/components/responses/ValidationError'

  /users:
    get:
      summary: List users (admin)
      operationId: listUsers
      security:
        - bearerAuth: []
      parameters:
        - name: role
          in: query
          schema:
            type: string
            enum: [client, worker, admin]
        - name: active
          in: query
          schema:
            type: boolean
        - name: limit
          in: query
          schema:
            type: integer
        - name: offset
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Users retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserProfile'
                  total:
                    type: integer
        '403':
          $ref: '#/components/responses/Forbidden'
          description: Only admins can list users.

  /users/{user_id}:
    description: Users may only access or update their own profile unless admin.
    parameters:
      - in: path
        name: user_id
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Get user profile
      operationId: getUserProfile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '404':
          $ref: '#/components/responses/NotFound'

    patch:
      summary: Update user profile
      operationId: updateUserProfile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserSchema'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/ValidationError'

    delete:
      summary: Delete a user (admin)
      operationId: deleteUser
      security:
        - bearerAuth: []
      responses:
        '204':
          description: User deleted successfully
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /users/{user_id}/role:
    parameters:
      - in: path
        name: user_id
        required: true
        schema:
          type: string
          format: uuid
    patch:
      summary: Update user role (admin only)
      operationId: updateUserRole
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [role]
              properties:
                role:
                  type: string
                  enum: [client, worker, admin]
      responses:
        '200':
          description: Role updated
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    NotFound:
      description: The specified resource was not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    UnauthorizedError:
      description: Authentication required or invalid credentials.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Conflict:
      description: Duplicate resource conflict.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ValidationError:
      description: The payload contains invalid values.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: The user is not authorized for this action.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Bad request parameters or token invalid/expired.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
          description: Domain-specific error code
        message:
          type: string
        details:
          type: object

    TokenResponse:
      type: object
      required:
        - access_token
        - token_type
        - expires_in
      properties:
        access_token:
          type: string
        token_type:
          type: string
          example: Bearer
        expires_in:
          type: integer
          description: seconds until access token expiry
        refresh_token:
          type: string
          description: Refresh token to obtain new access tokens


    RegisterUserSchema:
      type: object
      required:
        - name
        - email
        - password
        - role
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
          description: Password must meet strength requirements (min length, complexity)
        role:
          type: string
          enum: [client, worker]
        phone:
          type: string
        consent:
          type: boolean
          description: User consent to terms and privacy policy

    LoginSchema:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string

    UpdateUserSchema:
      type: object
      properties:
        name:
          type: string
        phone:
          type: string
        address:
          $ref: '#/components/schemas/Address'
        privacySettings:
          $ref: '#/components/schemas/PrivacySettings'

    Address:
      type: object
      properties:
        street:
          type: string
        city:
          type: string
        country:
          type: string

    PrivacySettings:
      type: object
      properties:
        showContactToClients:
          type: boolean
          default: false

    UserProfile:
      type: object
      required:
        - userId
        - name
        - email
        - role
      properties:
        userId:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
          format: email
        role:
          type: string
          enum: [client, worker, admin]
        phone:
          type: string
        address:
          $ref: '#/components/schemas/Address'
        privacySettings:
          $ref: '#/components/schemas/PrivacySettings'
        active:
          type: boolean
          default: true
        lastLoginAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

security:
  - bearerAuth: []
